#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = LAYOUT(
      LT(4,KC_Q), LT(3,KC_W), LT(2,KC_E), LT(1,KC_R),          KC_T,                                      KC_Y,   LT(1,KC_U), LT(2,KC_I), LT(3,KC_O),    LT(4,KC_P),
      LCTL(KC_A), LGUI(KC_S), LALT(KC_D), LSFT(KC_F),          KC_G,                                      KC_H,   RSFT(KC_J), RALT(KC_K), RGUI(KC_L), RCTL(KC_SCLN),
            KC_Z,       KC_X,       KC_C,       KC_V,          KC_B,      XXXXXXX,       XXXXXXX,         KC_N,         KC_M,    KC_COMM,     KC_DOT,       KC_SLSH,
         XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX, LT(2,KC_BSPC), LT(1,KC_ESC),  LT(1,KC_ENT), LT(2,KC_SPC),      XXXXXXX,    XXXXXXX,    XXXXXXX,       XXXXXXX,
    ),

  [1] = LAYOUT(
         KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                     KC_6, KC_7,    KC_8,    KC_9,    KC_0,
      XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                  CK_PPLS, KC_4,    KC_5,    KC_6, KC_PMNS,
      XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,KC_PAST, KC_1,    KC_2,    KC_3, KC_PSLS,
      XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,XXXXXXX, KC_0, XXXXXXX, XXXXXXX, XXXXXXX,
    ),

  [2] = LAYOUT(
      KC_EXLM,   KC_AT, KC_HASH,  KC_DLR, KC_PERC,                  KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN,
      KC_LCBR, KC_LBRC, KC_RBRC, KC_RCBR, XXXXXXX,                  KC_MINS,  KC_EQL, KC_NUBS,  KC_GRV, KC_QUOT,
        KC_LT, KC_LPRN, KC_RPRN,   KC_GT, XXXXXXX, XXXXXXX, XXXXXXX,KC_UNDS, KC_PLUS, KC_PIPE, KC_TILD, KC_DQUO,
      XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    ),

  [3] = LAYOUT(
      XXXXXXX, MS_WHLL, MS_WHLU, MS_WHLD, MS_WHLR,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
      XXXXXXX, MS_LEFT,   MS_UP, MS_DOWN, MS_RGHT,                   KC_LEFT, KC_DOWN,   KC_UP,KC_RIGHT, XXXXXXX,
      XXXXXXX, MS_BTN3, MS_BTN2, MS_BTN1, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
      XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    ),

  [4] = LAYOUT(
      XXXXXXX, KC_F10,  KC_F11,  KC_F12,  XXXXXXX,                   XXXXXXX, KC_PSCR, KC_SCRL, KC_PAUS, XXXXXXX,
      XXXXXXX,  KC_F7,   KC_F8,   KC_F9,  XXXXXXX,                   KC_HOME, KC_PGDN, KC_PGUP,  KC_END, XXXXXXX,
      XXXXXXX,  KC_F4,   KC_F5,   KC_F6,  XXXXXXX, QK_BOOT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
      XXXXXXX,  KC_F1,   KC_F2,   KC_F3,   KC_DEL,  KC_INS, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    )
};
